name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-20.04
            images: amd64/alpine

    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Docker Details
        if: runner.os != 'Windows'
        run: docker info

      - name: Run Images on ${{ matrix.os }}
        if: runner.os != 'Windows'
        run: docker run ${{ matrix.images }}

      - name: Skip step on Windows
        if: runner.os == 'Windows'
        run: echo "Skipping Docker run on Windows due to compatibility issues."
