name: Docker Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: portfolio-site

concurrency:
  group: workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Job-level timeout of 15 minutes
    strategy:
      matrix:
        tag: [latest, v1, dev]  # You can expand this list as needed
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        timeout-minutes: 2  # Step-level timeout of 2 minutes

      - name: Docker Login
        uses: docker/login-action@v2
        timeout-minutes: 3  # Step-level timeout of 3 minutes
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Build
        timeout-minutes: 10  # Step-level timeout of 10 minutes
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }} .
      
      - name: Docker Publish
        timeout-minutes: 5  # Step-level timeout of 5 minutes
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
  
  deploy:
    needs: docker
    if: ${{ contains(needs.docker.result, 'success') }}
    timeout-minutes: 10  # Job-level timeout of 10 minutes
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        timeout-minutes: 3  # Step-level timeout of 3 minutes
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Deploy Notification
        timeout-minutes: 1  # Step-level timeout of 1 minute
        run: echo "Docker image has been successfully published. Ready for deployment to production server."
      
      # Note: In a real production scenario, you would add steps here to deploy to your actual hosting environment
      # For example, using SSH to connect to your server and pull/run the new image